### ISSUE TITLE
session-file

### ISSUE THREAD

**Issue by custardcream** [nccgroup/umap2#12]
Hi all 

I have performed some fuzzing (nice tool) I have a kitty_***.log file with 'errors and failures' after running a complete fuzzing cycle (i assume errors/failures are worth further exploration) so running `umap2kitty -s keyboard.stages -k -h` tells me I can retest failed/error tests from a 'session-file', are the tests stored somewhere, do i need to create one, I'm missing something obvious im sure ;)

**Comment by BinyaminSharet** [comment]
Documenting the fuzzing process with Umap2 is still on my todo list, but I might get to it during the weekend.

The session file can be created by running umap2kitty with `-k "-s <session_file_name>"` and you will be able to retest failed/error cases from this session file (with `-k "-r <session_file_name>"`). This session file can also be used to resume the fuzzer if it was stopped in the middle.

If you know the test numbers with the issues, you can run them alone using `-k "-t 1,2,3"`

**Comment by custardcream** [comment]
thanks for the quick reply ! 

So i need to generate the session file during stage 2 of the readme eg. `umap2kitty -s keyboard.stages -k "-s <session_file_name>` ??

**Comment by BinyaminSharet** [comment]
Yup. I will try to update the documentation soon.

**Comment by custardcream** [comment]
great thank you, just to correct both our posts above, stage 2 should be - 
`umap2kitty -s keyboard.stages -k "-f <session_file_name>`

to generate a session-file not  -s

again thanks for your quick help !

**Comment by BinyaminSharet** [comment]
oops :) thanks, good point..

**Comment by BinyaminSharet** [comment]
Added fuzzing guide at: https://github.com/nccgroup/umap2/blob/master/docs/fuzzing.rst
Closing this issue, but would like to know what's missing.
