### ISSUE TITLE
How to fuzz a single descriptor

### ISSUE THREAD

**Issue by custardcream** [nccgroup/umap2#13]
Hi 

Once a stages file is created the fuzzer goes through the record flow and fuzzes all the descriptors the host is expecting (normal operation), is there a way to just fuzz a singular descripter eg. the configuration descriptor ?

**Comment by BinyaminSharet** [comment]
Yes. The stages file is actually a file with a list of stage names. You can edit it and remove anything besides the configuration_descriptor, and then umap2 will only fuzz the configuration descriptor.

Worth noting though - that if the configuration descriptor appears more than once, you probably want to keep it that way, as in many cases a descriptor is called twice - once for its length and once for the data, and so keeping it twice will tell the fuzzer to fuzz both stages.

**Comment by custardcream** [comment]
thanks for the quick reply !
