### ISSUE TITLE
pickle on python3 issue

### ISSUE THREAD

**Issue by lucasduffey** [nccgroup/umap2#14]
making an issue for feedback, rather than contributing a commit because I'm not 100% this problem is experienced by anyone else.

getting an issue with cPickle not existing in python3. cPickle IS NOT a package you can installl. My patch is below.
```
# line: https://github.com/nccgroup/umap2/blob/master/umap2/apps/vsscan.py#L45

import _pickle as cPickle
#import cPickle
```

**Comment by BinyaminSharet** [comment]
Please add this change to pull request #16 (and see my comments there as well)
